/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PitchingVelocityByAgeRouteImport } from './routes/pitching-velocity-by-age'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as HowToThrowHarderRouteImport } from './routes/how-to-throw-harder'
import { Route as HowToIncreaseExitVelocityRouteImport } from './routes/how-to-increase-exit-velocity'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BaseballWorkoutPlansRouteImport } from './routes/baseball-workout-plans'
import { Route as BaseballStrengthTrainingRouteImport } from './routes/baseball-strength-training'
import { Route as BaseballNutritionRouteImport } from './routes/baseball-nutrition'
import { Route as AveragePopTimeByAgeRouteImport } from './routes/average-pop-time-by-age'
import { Route as AverageExitVelocityByAgeRouteImport } from './routes/average-exit-velocity-by-age'
import { Route as AverageBatSpeedByAgeRouteImport } from './routes/average-bat-speed-by-age'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as CalculatorsSlugRouteImport } from './routes/calculators.$slug'
import { Route as AuthenticatedTrainingRouteImport } from './routes/_authenticated/training'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChartsRouteImport } from './routes/_authenticated/charts'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchingVelocityByAgeRoute = PitchingVelocityByAgeRouteImport.update({
  id: '/pitching-velocity-by-age',
  path: '/pitching-velocity-by-age',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToThrowHarderRoute = HowToThrowHarderRouteImport.update({
  id: '/how-to-throw-harder',
  path: '/how-to-throw-harder',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToIncreaseExitVelocityRoute =
  HowToIncreaseExitVelocityRouteImport.update({
    id: '/how-to-increase-exit-velocity',
    path: '/how-to-increase-exit-velocity',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseballWorkoutPlansRoute = BaseballWorkoutPlansRouteImport.update({
  id: '/baseball-workout-plans',
  path: '/baseball-workout-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseballStrengthTrainingRoute =
  BaseballStrengthTrainingRouteImport.update({
    id: '/baseball-strength-training',
    path: '/baseball-strength-training',
    getParentRoute: () => rootRouteImport,
  } as any)
const BaseballNutritionRoute = BaseballNutritionRouteImport.update({
  id: '/baseball-nutrition',
  path: '/baseball-nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const AveragePopTimeByAgeRoute = AveragePopTimeByAgeRouteImport.update({
  id: '/average-pop-time-by-age',
  path: '/average-pop-time-by-age',
  getParentRoute: () => rootRouteImport,
} as any)
const AverageExitVelocityByAgeRoute =
  AverageExitVelocityByAgeRouteImport.update({
    id: '/average-exit-velocity-by-age',
    path: '/average-exit-velocity-by-age',
    getParentRoute: () => rootRouteImport,
  } as any)
const AverageBatSpeedByAgeRoute = AverageBatSpeedByAgeRouteImport.update({
  id: '/average-bat-speed-by-age',
  path: '/average-bat-speed-by-age',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsSlugRoute = CalculatorsSlugRouteImport.update({
  id: '/calculators/$slug',
  path: '/calculators/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrainingRoute = AuthenticatedTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChartsRoute = AuthenticatedChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/average-bat-speed-by-age': typeof AverageBatSpeedByAgeRoute
  '/average-exit-velocity-by-age': typeof AverageExitVelocityByAgeRoute
  '/average-pop-time-by-age': typeof AveragePopTimeByAgeRoute
  '/baseball-nutrition': typeof BaseballNutritionRoute
  '/baseball-strength-training': typeof BaseballStrengthTrainingRoute
  '/baseball-workout-plans': typeof BaseballWorkoutPlansRoute
  '/blog': typeof BlogRoute
  '/features': typeof FeaturesRoute
  '/how-to-increase-exit-velocity': typeof HowToIncreaseExitVelocityRoute
  '/how-to-throw-harder': typeof HowToThrowHarderRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/pitching-velocity-by-age': typeof PitchingVelocityByAgeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teams': typeof TeamsRoute
  '/charts': typeof AuthenticatedChartsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/calculators/$slug': typeof CalculatorsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/average-bat-speed-by-age': typeof AverageBatSpeedByAgeRoute
  '/average-exit-velocity-by-age': typeof AverageExitVelocityByAgeRoute
  '/average-pop-time-by-age': typeof AveragePopTimeByAgeRoute
  '/baseball-nutrition': typeof BaseballNutritionRoute
  '/baseball-strength-training': typeof BaseballStrengthTrainingRoute
  '/baseball-workout-plans': typeof BaseballWorkoutPlansRoute
  '/blog': typeof BlogRoute
  '/features': typeof FeaturesRoute
  '/how-to-increase-exit-velocity': typeof HowToIncreaseExitVelocityRoute
  '/how-to-throw-harder': typeof HowToThrowHarderRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/pitching-velocity-by-age': typeof PitchingVelocityByAgeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teams': typeof TeamsRoute
  '/charts': typeof AuthenticatedChartsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/calculators/$slug': typeof CalculatorsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/average-bat-speed-by-age': typeof AverageBatSpeedByAgeRoute
  '/average-exit-velocity-by-age': typeof AverageExitVelocityByAgeRoute
  '/average-pop-time-by-age': typeof AveragePopTimeByAgeRoute
  '/baseball-nutrition': typeof BaseballNutritionRoute
  '/baseball-strength-training': typeof BaseballStrengthTrainingRoute
  '/baseball-workout-plans': typeof BaseballWorkoutPlansRoute
  '/blog': typeof BlogRoute
  '/features': typeof FeaturesRoute
  '/how-to-increase-exit-velocity': typeof HowToIncreaseExitVelocityRoute
  '/how-to-throw-harder': typeof HowToThrowHarderRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/pitching-velocity-by-age': typeof PitchingVelocityByAgeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teams': typeof TeamsRoute
  '/_authenticated/charts': typeof AuthenticatedChartsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/training': typeof AuthenticatedTrainingRoute
  '/calculators/$slug': typeof CalculatorsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/average-bat-speed-by-age'
    | '/average-exit-velocity-by-age'
    | '/average-pop-time-by-age'
    | '/baseball-nutrition'
    | '/baseball-strength-training'
    | '/baseball-workout-plans'
    | '/blog'
    | '/features'
    | '/how-to-increase-exit-velocity'
    | '/how-to-throw-harder'
    | '/leaderboards'
    | '/pitching-velocity-by-age'
    | '/reset-password'
    | '/sitemap.xml'
    | '/teams'
    | '/charts'
    | '/dashboard'
    | '/profile'
    | '/progress'
    | '/training'
    | '/calculators/$slug'
    | '/resources/$slug'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/average-bat-speed-by-age'
    | '/average-exit-velocity-by-age'
    | '/average-pop-time-by-age'
    | '/baseball-nutrition'
    | '/baseball-strength-training'
    | '/baseball-workout-plans'
    | '/blog'
    | '/features'
    | '/how-to-increase-exit-velocity'
    | '/how-to-throw-harder'
    | '/leaderboards'
    | '/pitching-velocity-by-age'
    | '/reset-password'
    | '/sitemap.xml'
    | '/teams'
    | '/charts'
    | '/dashboard'
    | '/profile'
    | '/progress'
    | '/training'
    | '/calculators/$slug'
    | '/resources/$slug'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/auth-callback'
    | '/average-bat-speed-by-age'
    | '/average-exit-velocity-by-age'
    | '/average-pop-time-by-age'
    | '/baseball-nutrition'
    | '/baseball-strength-training'
    | '/baseball-workout-plans'
    | '/blog'
    | '/features'
    | '/how-to-increase-exit-velocity'
    | '/how-to-throw-harder'
    | '/leaderboards'
    | '/pitching-velocity-by-age'
    | '/reset-password'
    | '/sitemap.xml'
    | '/teams'
    | '/_authenticated/charts'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/_authenticated/training'
    | '/calculators/$slug'
    | '/resources/$slug'
    | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AverageBatSpeedByAgeRoute: typeof AverageBatSpeedByAgeRoute
  AverageExitVelocityByAgeRoute: typeof AverageExitVelocityByAgeRoute
  AveragePopTimeByAgeRoute: typeof AveragePopTimeByAgeRoute
  BaseballNutritionRoute: typeof BaseballNutritionRoute
  BaseballStrengthTrainingRoute: typeof BaseballStrengthTrainingRoute
  BaseballWorkoutPlansRoute: typeof BaseballWorkoutPlansRoute
  BlogRoute: typeof BlogRoute
  FeaturesRoute: typeof FeaturesRoute
  HowToIncreaseExitVelocityRoute: typeof HowToIncreaseExitVelocityRoute
  HowToThrowHarderRoute: typeof HowToThrowHarderRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  PitchingVelocityByAgeRoute: typeof PitchingVelocityByAgeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamsRoute: typeof TeamsRoute
  CalculatorsSlugRoute: typeof CalculatorsSlugRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitching-velocity-by-age': {
      id: '/pitching-velocity-by-age'
      path: '/pitching-velocity-by-age'
      fullPath: '/pitching-velocity-by-age'
      preLoaderRoute: typeof PitchingVelocityByAgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-throw-harder': {
      id: '/how-to-throw-harder'
      path: '/how-to-throw-harder'
      fullPath: '/how-to-throw-harder'
      preLoaderRoute: typeof HowToThrowHarderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-increase-exit-velocity': {
      id: '/how-to-increase-exit-velocity'
      path: '/how-to-increase-exit-velocity'
      fullPath: '/how-to-increase-exit-velocity'
      preLoaderRoute: typeof HowToIncreaseExitVelocityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baseball-workout-plans': {
      id: '/baseball-workout-plans'
      path: '/baseball-workout-plans'
      fullPath: '/baseball-workout-plans'
      preLoaderRoute: typeof BaseballWorkoutPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baseball-strength-training': {
      id: '/baseball-strength-training'
      path: '/baseball-strength-training'
      fullPath: '/baseball-strength-training'
      preLoaderRoute: typeof BaseballStrengthTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baseball-nutrition': {
      id: '/baseball-nutrition'
      path: '/baseball-nutrition'
      fullPath: '/baseball-nutrition'
      preLoaderRoute: typeof BaseballNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/average-pop-time-by-age': {
      id: '/average-pop-time-by-age'
      path: '/average-pop-time-by-age'
      fullPath: '/average-pop-time-by-age'
      preLoaderRoute: typeof AveragePopTimeByAgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/average-exit-velocity-by-age': {
      id: '/average-exit-velocity-by-age'
      path: '/average-exit-velocity-by-age'
      fullPath: '/average-exit-velocity-by-age'
      preLoaderRoute: typeof AverageExitVelocityByAgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/average-bat-speed-by-age': {
      id: '/average-bat-speed-by-age'
      path: '/average-bat-speed-by-age'
      fullPath: '/average-bat-speed-by-age'
      preLoaderRoute: typeof AverageBatSpeedByAgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/$slug': {
      id: '/calculators/$slug'
      path: '/calculators/$slug'
      fullPath: '/calculators/$slug'
      preLoaderRoute: typeof CalculatorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/training': {
      id: '/_authenticated/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthenticatedTrainingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/charts': {
      id: '/_authenticated/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof AuthenticatedChartsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChartsRoute: typeof AuthenticatedChartsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedTrainingRoute: typeof AuthenticatedTrainingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChartsRoute: AuthenticatedChartsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedTrainingRoute: AuthenticatedTrainingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AverageBatSpeedByAgeRoute: AverageBatSpeedByAgeRoute,
  AverageExitVelocityByAgeRoute: AverageExitVelocityByAgeRoute,
  AveragePopTimeByAgeRoute: AveragePopTimeByAgeRoute,
  BaseballNutritionRoute: BaseballNutritionRoute,
  BaseballStrengthTrainingRoute: BaseballStrengthTrainingRoute,
  BaseballWorkoutPlansRoute: BaseballWorkoutPlansRoute,
  BlogRoute: BlogRoute,
  FeaturesRoute: FeaturesRoute,
  HowToIncreaseExitVelocityRoute: HowToIncreaseExitVelocityRoute,
  HowToThrowHarderRoute: HowToThrowHarderRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  PitchingVelocityByAgeRoute: PitchingVelocityByAgeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamsRoute: TeamsRoute,
  CalculatorsSlugRoute: CalculatorsSlugRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
